{
 "title": "my_custom_dash",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "cluster", "query": "nodefacts_system" },
   { "name": "stype", "query": "nodefacts_system" }
  ]
 },
 "panels": [
  {
   "title": "CPU Cores for $stype at $cluster",
   "type": "singlestat",
   "description": "Total CPU cores",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(count(count(node_cpu * on (instance) group_left nodefacts_system{role=$stype,cluster=$cluster}) without (mode)) without (cpu))"
    }
   ]
  },
  {
   "title": "Total Memory for $stype at $cluster",
   "type": "singlestat",
   "description": "Total memory",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 0 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    { "expr": "sum(node_memory_MemTotal)" }
   ]
  },
  {
   "title": "Load Average",
   "type": "graph",
   "description": "LoadAverage divided by total number of processes.",
   "gridPos": { "h": 8, "w": 22, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(node_load1 * on (instance) group_left nodefacts_system{role=$stype,cluster=$cluster}) by (node_load1)\n/\nsum(count(count(node_cpu) without (mode)) without (cpu) * on (instance) group_left nodefacts_system{role=$stype,cluster=$cluster})",
     "legendFormat": "1min"
    },
    {
     "expr": "avg(node_load5 * on (instance) group_left nodefacts_system{role=$stype,cluster=$cluster}) by (node_load1)\n/\nsum(count(count(node_cpu) without (mode)) without (cpu) * on (instance) group_left nodefacts_system{role=$stype,cluster=$cluster})",
     "legendFormat": "5min"
    },
    {
     "expr": "avg(node_load15 * on (instance) group_left nodefacts_system{role=$stype,cluster=$cluster}) by (node_load1)\n/\nsum(count(count(node_cpu) without (mode)) without (cpu) * on (instance) group_left nodefacts_system{role=$stype,cluster=$cluster})",
     "legendFormat": "15min"
    }
   ]
  },
  {
   "title": "CPU Usage Average",
   "type": "graph",
   "description": "Average CPU usage",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg(rate(node_cpu[5m]) * on (instance) group_left nodefacts_system{role=$stype,cluster=$cluster}) by (mode)\n"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "description": "Memory Usage servers on cluster 13, type web servers.",
   "gridPos": { "h": 8, "w": 21, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(\n  sum(node_memory_MemTotal * on (instance) nodefacts_system{cluster=$cluster,role=$stype}) \n  -\n  (\n    sum(node_memory_MemFree * on (instance) nodefacts_system{cluster=$cluster,role=$stype})\n  +\n    sum(node_memory_Buffers * on (instance) nodefacts_system{cluster=$cluster,role=$stype})\n  +\n    sum(node_memory_Cached * on (instance) nodefacts_system{cluster=$cluster,role=$stype})\n  )\n)\n/\nsum(node_memory_MemTotal * on (instance) nodefacts_system{cluster=$cluster,role=$stype})",
     "legendFormat": "Used"
    },
    {
     "expr": "sum(node_memory_MemFree * on (instance) nodefacts_system{cluster=$cluster,role=$stype})\n/sum(node_memory_MemTotal * on (instance) nodefacts_system{cluster=$cluster,role=$stype})",
     "legendFormat": "Free"
    },
    {
     "expr": "sum(node_memory_Buffers * on (instance) nodefacts_system{cluster=$cluster,role=$stype})\n/sum(node_memory_MemTotal * on (instance) nodefacts_system{cluster=$cluster,role=$stype})",
     "legendFormat": "Buffers"
    },
    {
     "expr": "sum(node_memory_Cached * on (instance) nodefacts_system{cluster=$cluster,role=$stype})\n/sum(node_memory_MemTotal * on (instance) nodefacts_system{cluster=$cluster,role=$stype})",
     "legendFormat": "Cached"
    }
   ]
  }
 ]
}